language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script: 
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --verbose; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --verbose --coverage-text --coverage-clover /tmp/xml/coverage.xml; fi;'

matrix: 
  allow_failures: 
    - php: 5.6
    - php: hhvm
  fast_finish: true
notififation:   
  on_success: never
  on_failure: always
